name: Test and Build Workflow
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          echo "Testing 1 + 1 logic"
          pytest -c "assert 1 + 1 == 2"
  build-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Build Application if Tests Pass
        run: echo "Building application after successful tests"

