name: Testing and Building Workflow
on: push
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout code
       uses: actions/checkout@v2
      -name: Set up Python
       uses: actions/setup-python@v2
       with:
        python -m pip install -- upgrade pip
        pip install pytest
        - name: Run tests
        run: pytest test_app.py

  build_job:
    runs-on: ubuntu-latest
    needs: test_job
    steps:
      - name: Build Application
        run: echo "Building the application..."